package risk.engine.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import risk.engine.db.entity.Indicator;

public interface IndicatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    long countByExample(IndicatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int deleteByExample(IndicatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int insert(Indicator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int insertSelective(Indicator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    List<Indicator> selectByExample(IndicatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    Indicator selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByExampleSelective(@Param("record") Indicator record, @Param("example") IndicatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByExample(@Param("record") Indicator record, @Param("example") IndicatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByPrimaryKeySelective(Indicator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indicator
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByPrimaryKey(Indicator record);
}