package risk.engine.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import risk.engine.db.entity.ListLibrary;

public interface ListLibraryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_library
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    long countByExample(ListLibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_library
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int deleteByExample(ListLibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_library
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_library
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int insert(ListLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_library
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int insertSelective(ListLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_library
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    List<ListLibrary> selectByExampleWithBLOBs(ListLibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_library
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    List<ListLibrary> selectByExample(ListLibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_library
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    ListLibrary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_library
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByExampleSelective(@Param("record") ListLibrary record, @Param("example") ListLibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_library
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("record") ListLibrary record, @Param("example") ListLibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_library
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByExample(@Param("record") ListLibrary record, @Param("example") ListLibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_library
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByPrimaryKeySelective(ListLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_library
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(ListLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_library
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByPrimaryKey(ListLibrary record);
}