package risk.engine.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import risk.engine.db.entity.ListData;

public interface ListDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_data
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    long countByExample(ListDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_data
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int deleteByExample(ListDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_data
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_data
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int insert(ListData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_data
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int insertSelective(ListData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_data
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    List<ListData> selectByExampleWithBLOBs(ListDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_data
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    List<ListData> selectByExample(ListDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_data
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    ListData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_data
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByExampleSelective(@Param("record") ListData record, @Param("example") ListDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_data
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("record") ListData record, @Param("example") ListDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_data
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByExample(@Param("record") ListData record, @Param("example") ListDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_data
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByPrimaryKeySelective(ListData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_data
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(ListData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_data
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByPrimaryKey(ListData record);
}