package risk.engine.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import risk.engine.db.entity.PenaltyRecord;

public interface PenaltyRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty_record
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    long countByExample(PenaltyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty_record
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int deleteByExample(PenaltyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty_record
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty_record
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int insert(PenaltyRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty_record
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int insertSelective(PenaltyRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty_record
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    List<PenaltyRecordWithBLOBs> selectByExampleWithBLOBs(PenaltyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty_record
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    List<PenaltyRecord> selectByExample(PenaltyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty_record
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    PenaltyRecordWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty_record
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByExampleSelective(@Param("record") PenaltyRecordWithBLOBs record, @Param("example") PenaltyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty_record
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("record") PenaltyRecordWithBLOBs record, @Param("example") PenaltyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty_record
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByExample(@Param("record") PenaltyRecord record, @Param("example") PenaltyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty_record
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByPrimaryKeySelective(PenaltyRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty_record
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(PenaltyRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty_record
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByPrimaryKey(PenaltyRecord record);
}