package risk.engine.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import risk.engine.db.entity.Penalty;

public interface PenaltyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    long countByExample(PenaltyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int deleteByExample(PenaltyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int insert(PenaltyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int insertSelective(PenaltyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    List<PenaltyWithBLOBs> selectByExampleWithBLOBs(PenaltyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    List<Penalty> selectByExample(PenaltyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    PenaltyWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByExampleSelective(@Param("record") PenaltyWithBLOBs record, @Param("example") PenaltyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("record") PenaltyWithBLOBs record, @Param("example") PenaltyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByExample(@Param("record") Penalty record, @Param("example") PenaltyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByPrimaryKeySelective(PenaltyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(PenaltyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penalty
     *
     * @mbg.generated Sun Mar 16 12:23:12 CST 2025
     */
    int updateByPrimaryKey(Penalty record);
}