spring:
  datasource:
    url: jdbc:mysql://43.156.132.139:3306/risk?allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: dcr
    password: dcr
  redis:
    host: 43.156.132.139
    password: dcr
    timeout: 2000ms
    database: 1  #默认有16个db(集群模式用hash槽代替)，这里配置具体使用的db，默认是0

rocketmq:
  name-server: rocketmq-namesrv:9876
  consumer:
    topic: engine_result_topic
    group: consumer-group-engine-save-db
  producer:
    group: producer-group-engine
    send-message-timeout: 3000

elasticsearch:
  url: http://106.55.233.79:9200
  username: elastic
  password: ELASTIC_dcr_0315

logging:
  file:
    path: /app/logs