spring:
  application:
    name: RISK-ENGINE-X-REST
  profiles:
    active: dev

server:
  port: 8088
  servlet:
    context-path: /api

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: risk.engine.db.entity
