spring:
  datasource:
    url: jdbc:mysql://43.156.132.139:3306/risk?allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: dcr
    password: dcr
  redis:
    host: 43.156.132.139
    password: dcr
    timeout: 2000ms
    database: 1  #默认有16个db(集群模式用hash槽代替)，这里配置具体使用的db，默认是0
  kafka:
    bootstrap-servers: 43.156.132.139:9093
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

customer:
  kafka:
    topic: engine_result_topic_test

elasticsearch:
  url: http://106.55.233.79:9200
  username: elastic
  password: ELASTIC_dcr_0315

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: risk.engine.db.entity

logging:
  file:
    path: /Users/dongchunrong/Documents/project/data/logs
