spring:
  datasource:
    url: jdbc:mysql://10.1.8.2:3306/risk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: dcr
    password: dcr
  redis:
    host: 10.1.8.2
    password: dcr
    timeout: 2000ms
    database: 1  #默认有16个db(集群模式用hash槽代替)，这里配置具体使用的db，默认是0
rocketmq:
  name-server: rocketmq-namesrv
  consumer:
    group: consumer-group-test1
  producer:
    group: producer-test-group1
    send-message-timeout: 3000

elasticsearch:
  url: http://10.1.8.2:9200
  username: elastic
  password: ELASTIC_dcr_0315

logging:
  file:
    path: /opt/risk-engine-x/logs
