spring:
  datasource:
    url: jdbc:mysql://10.3.0.15:3306/risk?allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: dcr
    password: dcr
  redis:
    host: 10.3.0.15
    password: dcr
    timeout: 2000ms
    database: 1  #默认有16个db(集群模式用hash槽代替)，这里配置具体使用的db，默认是0
  kafka:
    bootstrap-servers: 43.156.132.139:9093
    consumer:
      group-id: canal-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

customer:
  kafka:
    topic: engine_result_topic_prod

elasticsearch:
  url: http://106.55.233.79:9200
  username: elastic
  password: ELASTIC_dcr_0315

logging:
  file:
    path: /app/logs