host:
  ip: 43.163.107.28

spring:
  datasource:
    url: jdbc:mysql://${host.ip}:3306/risk?allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: dcr
    password: dcr
  redis:
    host: ${host.ip}
    password: dcr
    timeout: 2000ms
    database: 1  #默认有16个db(集群模式用hash槽代替)，这里配置具体使用的db，默认是0
  kafka:
    bootstrap-servers: ${host.ip}:9093
    consumer:
      group-id: canal-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

customer:
  kafka:
    topic: engine_result_topic_test

elasticsearch:
  url: http://${host.ip}:9200
  username: elastic
  password: ELASTIC_dcr_0315

xxl:
  job:
    admin:
      addresses: http://106.55.233.79:8001/xxl-job-admin  # XXL-Job Admin 的地址
      accessToken: xxl-job-token
    executor:
      appname: xxl-job-executor-x  # 执行器名称，需与 Admin 中配置一致
      address: https://f566-165-154-20-168.ngrok-free.app # 可选，自动注册时留空
      #ip: 103.167.134.66 # 可选，默认自动获取
      #port: 9999  # 执行器端口，需与 Docker 配置一致
      logpath: /Users/dongchunrong/Documents/project/data/logs/risk-engine-job  # 日志存储路径
      logretentiondays: 7  # 日志保留天数

logging:
  file:
    path: /Users/dongchunrong/Documents/project/data/logs

