name: Build and Push Docker Images

# 触发条件：推送代码到 main 分支或手动触发
on:
  push:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发构建

# 环境变量，方便复用
env:
  DOCKERHUB_USERNAME: bbxydcr22  # 替换为你的 Docker Hub 用户名
  IMAGE_NAME: risk-engine-x      # 镜像名称

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. 设置 QEMU（用于多平台构建）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. 设置 Docker Buildx（支持多平台构建和缓存）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 5. 提取元数据（用于生成动态标签）
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=job-latest,enable=${{ github.event_name == 'push' && github.ref_name == 'main' }}
            type=raw,value=rest-latest,enable=${{ github.event_name == 'push' && github.ref_name == 'main' }}
            type=sha,prefix=job-,enable=${{ github.event_name == 'push' }}
            type=sha,prefix=rest-,enable=${{ github.event_name == 'push' }}

      # 6. 构建并推送 risk-engine-job 镜像
      - name: Build and Push risk-engine-job
        uses: docker/build-push-action@v5
        with:
          context: risk-engine-job/
          file: risk-engine-job/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:job-latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:job-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push risk-engine-rest
        uses: docker/build-push-action@v5
        with:
          context: risk-engine-rest/
          file: risk-engine-rest/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:rest-latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:rest-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max